site_name: Start

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our site and whether users
      find what they're searching for. With your consent, you're helping us to
      make our site better.

copyright: >
  Copyright &copy; 2023 Rick Lan –
  <a href="#__consent">Change cookie settings</a>
